# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt

  settings:
    goimports:
      local-prefixes: [github.com/scanoss/crypto-finder]

linters:
  enable:
    # Enabled by default
    - errcheck # Checks for unchecked errors
    - govet # Reports suspicious constructs
    - ineffassign # Detects ineffectual assignments
    - staticcheck # Comprehensive static analysis
    - unused # Checks for unused code

    # Error handling & bugs
    - errorlint # Find code that will cause problems with error wrapping
    - nilerr # Finds code that returns nil even if error is not nil

    # Performance
    - prealloc # Finds slice declarations that could potentially be pre-allocated
    - bodyclose # Checks whether HTTP response body is closed successfully

    # Style & code quality
    - revive # Fast, configurable, extensible, flexible linter
    - unconvert # Removes unnecessary type conversions
    - unparam # Reports unused function parameters
    - whitespace # Checks for unnecessary newlines
    - misspell # Finds commonly misspelled English words

    # Code complexity
    - gocognit # Computes and checks cognitive complexity
    - gocyclo # Computes and checks cyclomatic complexity
    - funlen # Checks function length
    - nestif # Reports deeply nested if statements

    # Potential bugs & best practices
    - goconst # Finds repeated strings that could be constants
    - gocritic # Comprehensive and opinionated linter
    - gosec # Security-focused linter
    - noctx # Finds HTTP requests without context.Context
    - sqlclosecheck # Checks sql.Rows and sql.Stmt are closed

    # Code correctness
    - exhaustive # Checks exhaustiveness of enum switch statements
    - makezero # Finds slice declarations with non-zero initial length
    - predeclared # Finds code that shadows predeclared identifiers
    - reassign # Checks that package variables are not reassigned
    - usestdlibvars # Detects the possibility to use standard lib variables

    # Comments & documentation
    - godot # Checks if comments end in a period

    # Linter management
    - nolintlint # Reports ill-formed or insufficient nolint directives

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close

    errorlint:
      errorf: true
      asserts: true
      comparison: true

    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: false

    funlen:
      lines: 120
      statements: 60
      ignore-comments: true

    gocognit:
      min-complexity: 20

    gocyclo:
      min-complexity: 15

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      disabled-checks:
        - whyNoLint
        - unnamedResult
      settings:
        hugeParam:
          sizeThreshold: 256

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G204 # Audit use of command execution - we'll check these manually
        - G304 # File path provided as taint input - check manually

    govet:
      enable-all: true
      disable:
        - fieldalignment # Can be too noisy
        - shadow # Often produces false positives

    misspell:
      locale: US

    nestif:
      min-complexity: 5

    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true

    prealloc:
      simple: true
      range-loops: true
      for-loops: true

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
          arguments:
            - ["ID"]
            - ["api"]
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    staticcheck:
      checks: ["all"]

    unparam:
      check-exported: false

  exclusions:
    warn-unused: false

    rules:
      - path: _test\.go
        linters:
          - gocognit
          - gocyclo
          - funlen
          - goconst
          - gosec
          - errcheck

      # Exclude godot for TODO comments
      - source: "// TODO"
        linters:
          - godot

      # Allow complex main functions
      - path: cmd/
        linters:
          - funlen
          - gocognit

    paths:
      - vendor
      - third_party
      - ".*\\.pb\\.go$"
      - ".*_gen\\.go$"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
