//go:build ignore

// generate_fixture.go generates the many_functions.java fixture used by
// inference performance benchmarks.
//
// Usage: go run generate_fixture.go
// Or via go generate: //go:generate go run generate_fixture.go

package main

import (
	"fmt"
	"os"
	"strings"
)

//go:generate go run generate_fixture.go

func main() {
	var sb strings.Builder

	sb.WriteString("package perf;\n\n")
	sb.WriteString("import javax.crypto.spec.SecretKeySpec;\n")
	sb.WriteString("import javax.crypto.KeyGenerator;\n\n")
	sb.WriteString("/** PerfFixture — 200 methods for inference benchmarking.\n")
	sb.WriteString(" * Generated by generate_fixture.go — DO NOT EDIT MANUALLY.\n")
	sb.WriteString(" */\n")
	sb.WriteString("public class PerfFixture {\n\n")
	sb.WriteString("    private byte[] bytes = new byte[16];\n\n")

	// 60 constructor-return methods (indices 0-59)
	for i := 0; i < 60; i++ {
		sb.WriteString(fmt.Sprintf("    public Object wrap%d() {\n", i))
		sb.WriteString("        return new SecretKeySpec(bytes, \"AES\");\n")
		sb.WriteString("    }\n\n")
	}

	// 40 KB-direct methods (indices 60-99) — use instance variable for correct callee resolution
	sb.WriteString("    private KeyGenerator kg;\n\n")
	for i := 60; i < 100; i++ {
		sb.WriteString(fmt.Sprintf("    public Object getKey%d() throws Exception {\n", i))
		sb.WriteString("        return kg.generateKey();\n")
		sb.WriteString("    }\n\n")
	}

	// 50 delegate methods (indices 100-149): return wrap(N mod 60)
	for i := 100; i < 150; i++ {
		n := i % 60
		sb.WriteString(fmt.Sprintf("    public Object delegate%d() {\n", i))
		sb.WriteString(fmt.Sprintf("        return wrap%d();\n", n))
		sb.WriteString("    }\n\n")
	}

	// 30 chain methods (indices 150-179): return delegate(N mod 50 + 100)
	for i := 150; i < 180; i++ {
		n := (i % 50) + 100
		sb.WriteString(fmt.Sprintf("    public Object chain%d() {\n", i))
		sb.WriteString(fmt.Sprintf("        return delegate%d();\n", n))
		sb.WriteString("    }\n\n")
	}

	// 20 pass-through methods (indices 180-199): return literal — no inference
	for i := 180; i < 200; i++ {
		sb.WriteString(fmt.Sprintf("    public Object pass%d() {\n", i))
		sb.WriteString("        return \"not-a-key\";\n")
		sb.WriteString("    }\n\n")
	}

	sb.WriteString("}\n")

	outPath := "many_functions.java"
	if err := os.WriteFile(outPath, []byte(sb.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s\n", outPath)
}
