// Copyright (C) 2026 SCANOSS.COM
// SPDX-License-Identifier: GPL-2.0-only
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; version 2.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

package callgraph

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/scanoss/crypto-finder/internal/skip"
)

func TestBuilder_SkipsShadedGeneratedJavaStubs(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	src := filepath.Join(root, "src", "main", "java", "com", "example")
	shaded := filepath.Join(root, "src", "main", "java", "io", "grpc", "xds", "shaded", "io", "envoyproxy")
	for _, dir := range []string{src, shaded} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", dir, err)
		}
	}
	writeCallgraphFixture(t, filepath.Join(src, "Cipher.java"), `package com.example;
public class Cipher {
  public void encrypt() {}
}
`)
	writeCallgraphFixture(t, filepath.Join(src, "FooOuterClass.java"), `package com.example;
public class FooOuterClass {
  public void parse() {}
}
`)
	writeCallgraphFixture(t, filepath.Join(src, "Messages.java"), `// Generated by the protocol buffer compiler.  DO NOT EDIT!
package com.example;
public class Messages {
  public void parse() {}
}
`)
	writeCallgraphFixture(t, filepath.Join(shaded, "Address.java"), `package io.grpc.xds.shaded.io.envoyproxy;
public class Address {
  public void parse() {}
}
`)

	graph, err := NewBuilder(NewJavaParser()).BuildFromDirectories(
		[]PackageDir{{Dir: root, ImportPath: "com.example"}}, nil)
	if err != nil {
		t.Fatalf("BuildFromDirectories: %v", err)
	}
	paths := functionFilePaths(graph)
	if !containsPathSuffix(paths, "Cipher.java") {
		t.Fatalf("authored Cipher.java missing from graph, files=%v", paths)
	}
	for _, banned := range []string{"shaded", "FooOuterClass.java", "Messages.java", "Address.java"} {
		if containsPathSuffix(paths, banned) {
			t.Errorf("generated/shaded %q must not appear in the graph, files=%v", banned, paths)
		}
	}
}

func TestBuilder_SkipsPythonProtobufStubs(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCallgraphFixture(t, filepath.Join(root, "crypto.py"), "def encrypt():\n    return None\n")
	writeCallgraphFixture(t, filepath.Join(root, "api_pb2.py"), "def parse():\n    return None\n")
	writeCallgraphFixture(t, filepath.Join(root, "api_pb2_grpc.py"), "def serve():\n    return None\n")

	graph, err := NewBuilderForEcosystem("python", NewPythonParser()).BuildFromDirectories(
		[]PackageDir{{Dir: root, ImportPath: "app"}}, nil)
	if err != nil {
		t.Fatalf("BuildFromDirectories: %v", err)
	}
	paths := functionFilePaths(graph)
	if !containsPathSuffix(paths, "crypto.py") {
		t.Fatalf("authored crypto.py missing from graph, files=%v", paths)
	}
	for _, banned := range []string{"api_pb2.py", "api_pb2_grpc.py"} {
		if containsPathSuffix(paths, banned) {
			t.Errorf("generated stub %q must not appear in the graph, files=%v", banned, paths)
		}
	}
}

func TestBuilder_NoDefaultMatcherKeepsGeneratedStubs(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeCallgraphFixture(t, filepath.Join(root, "crypto.py"), "def encrypt():\n    return None\n")
	writeCallgraphFixture(t, filepath.Join(root, "api_pb2.py"), "def parse():\n    return None\n")

	builder := NewBuilderForEcosystem("python", NewPythonParser())
	builder.SetSkipMatcher(skip.NewMatcher(nil, false))
	graph, err := builder.BuildFromDirectories([]PackageDir{{Dir: root, ImportPath: "app"}}, nil)
	if err != nil {
		t.Fatalf("BuildFromDirectories: %v", err)
	}
	paths := functionFilePaths(graph)
	if !containsPathSuffix(paths, "crypto.py") || !containsPathSuffix(paths, "api_pb2.py") {
		t.Fatalf("--no-default-exclusions must keep generated stubs, files=%v", paths)
	}
}

func writeCallgraphFixture(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func functionFilePaths(graph *CallGraph) []string {
	paths := make([]string, 0, len(graph.Functions))
	for _, fn := range graph.Functions {
		paths = append(paths, fn.FilePath)
	}
	return paths
}

func containsPathSuffix(paths []string, suffix string) bool {
	for _, p := range paths {
		if strings.Contains(p, suffix) {
			return true
		}
	}
	return false
}
