package callgraph

// inference_perf_test.go — Performance benchmarks and overhead assertion for
// the InferReturnTypes post-build pass.
//
// The performance fixture is the 200-method Java class generated by
// testdata/inference_perf/generate_fixture.go.
//
// Acceptance criterion (from spec): the inference pass MUST add less than
// 10% to the total call graph build time on the representative fixture.

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/scanoss/crypto-finder/internal/callgraph/contracts"
)

// perfFixtureDir returns the path to the inference_perf testdata directory.
func perfFixtureDir(t testing.TB) string {
	t.Helper()
	// The test runs from the package directory, so testdata is relative.
	dir := filepath.Join("testdata", "inference_perf")
	if _, err := os.Stat(filepath.Join(dir, "many_functions.java")); err != nil {
		t.Skipf("performance fixture not found at %s/many_functions.java (run generate_fixture.go first)", dir)
	}
	return dir
}

// BenchmarkBuildWithInference measures the full build pipeline including the
// inference pass.
func BenchmarkBuildWithInference(b *testing.B) {
	dir := perfFixtureDir(b)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		builder := NewBuilder(NewJavaParser())
		_, err := builder.BuildFromDirectories(
			[]PackageDir{{Dir: dir, ImportPath: "perf"}},
			nil,
		)
		if err != nil {
			b.Fatalf("BuildFromDirectories (with inference): %v", err)
		}
	}
}

// BenchmarkBuildWithoutInference measures the build pipeline WITHOUT the
// inference pass by using the inferenceDisabled seam serially (single-goroutine).
// This benchmark does NOT run in parallel with other tests.
func BenchmarkBuildWithoutInference(b *testing.B) {
	dir := perfFixtureDir(b)

	// Set seam; will be reset in b.Cleanup.
	inferenceDisabled = true
	b.Cleanup(func() { inferenceDisabled = false })

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		builder := NewBuilder(NewJavaParser())
		_, err := builder.BuildFromDirectories(
			[]PackageDir{{Dir: dir, ImportPath: "perf"}},
			nil,
		)
		if err != nil {
			b.Fatalf("BuildFromDirectories (without inference): %v", err)
		}
	}
}

// TestPerformance_InferenceOverhead asserts that the inference pass adds
// less than 10% overhead to the total build time.
//
// This test measures performance by:
//  1. Parsing the 200-function fixture to build a CallGraph (build cost).
//  2. Running InferReturnTypes separately to measure inference cost.
//  3. Computing inference_time / build_time ratio and asserting < 10%.
//
// This approach avoids the global-seam race condition that would arise if we
// used inferenceDisabled while parallel tests are running.
func TestPerformance_InferenceOverhead(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping performance test in short mode")
	}

	dir := perfFixtureDir(t)
	const iterations = 5

	kb, err := contracts.LoadEmbedded("java")
	if err != nil {
		t.Fatalf("LoadEmbedded(\"java\"): %v", err)
	}

	var buildTotal, inferTotal time.Duration

	for i := 0; i < iterations; i++ {
		// Build phase — parse + caller-index + fluent-chain resolution.
		// We skip inference here by building the graph without InferReturnTypes.
		// We measure build time by using the internal analyzeDir path via a
		// direct JavaParser call + manual graph assembly.
		buildStart := time.Now()
		p := NewJavaParser()
		analyses, err := p.ParseDirectory(dir, "perf")
		if err != nil {
			t.Fatalf("ParseDirectory: %v", err)
		}
		graph := &CallGraph{
			Functions:     make(map[string]*FunctionDecl),
			Callers:       make(map[string][]string),
			TypeHierarchy: make(map[string][]string),
		}
		for _, fa := range analyses {
			for j := range fa.Functions {
				fn := &fa.Functions[j]
				graph.Functions[fn.ID.String()] = fn
			}
		}
		// Build caller index (approximating builder.buildCallerIndex)
		for _, fn := range graph.Functions {
			for _, call := range fn.Calls {
				calleeKey := call.Callee.String()
				graph.Callers[calleeKey] = append(graph.Callers[calleeKey], fn.ID.String())
			}
		}
		buildTotal += time.Since(buildStart)

		// Inference phase — measure InferReturnTypes in isolation.
		inferStart := time.Now()
		if err := InferReturnTypes(graph, kb); err != nil {
			t.Fatalf("InferReturnTypes: %v", err)
		}
		inferTotal += time.Since(inferStart)
	}

	buildAvg := buildTotal / iterations
	inferAvg := inferTotal / iterations

	if buildAvg <= 0 {
		t.Fatalf("build average duration is 0 — measurement failed")
	}

	overheadPct := float64(inferAvg) / float64(buildAvg) * 100.0

	t.Logf("avg build time (parse+index):  %.2f ms", float64(buildAvg)/1e6)
	t.Logf("avg inference time:            %.2f ms", float64(inferAvg)/1e6)
	t.Logf("inference overhead:            %.2f%%", overheadPct)

	const maxOverheadPct = 10.0
	if overheadPct > maxOverheadPct {
		t.Errorf("inference overhead %.2f%% exceeds %.0f%% threshold (build=%.2fms, inference=%.2fms)",
			overheadPct, maxOverheadPct, float64(buildAvg)/1e6, float64(inferAvg)/1e6)
	}
}
