// Copyright 2025 SCANOSS
//
// SPDX-License-Identifier: Apache-2.0

// Package deduplicator provides functionality to deduplicate cryptographic assets
// based on their identity in the source code.
package deduplicator

import (
	"fmt"

	"github.com/scanoss/crypto-finder/internal/entities"
)

// assetGroupKey represents a unique identity for a cryptographic asset within a file.
// Assets with different identities (e.g., different algorithmFamily or algorithmName)
// at the same location are considered distinct and will not be merged.
// Assets with the same identity but at different locations are also kept separate.
type assetGroupKey struct {
	filePath  string
	assetKey  string // Generated by CryptographicAsset.GetKey()
	startLine int
	endLine   int
}

// String returns a string representation of the asset group key for debugging.
func (k assetGroupKey) String() string {
	return fmt.Sprintf("%s[%s@%d:%d]", k.filePath, k.assetKey, k.startLine, k.endLine)
}

// DeduplicateInterimReport removes duplicate CryptographicAssets that share
// the same identity (file path + asset key + location). When duplicates are found,
// their metadata and rule information are merged into a single asset.
//
// The deduplication process:
//  1. Groups assets by (file_path, asset_key, start_line, end_line) tuple, where
//     asset_key is generated by CryptographicAsset.GetKey() based on asset-type-specific
//     identifying fields
//  2. For each group, merges all assets into one representative asset
//  3. Preserves all unique metadata values from merged assets
//  4. Merges all unique rules from all assets in the group
//
// Assets with different identifying characteristics (e.g., different algorithmFamily
// or algorithmName) or at different locations are kept separate to prevent metadata confusion.
//
// This function modifies the report in-place and returns it for convenience.
func DeduplicateInterimReport(report *entities.InterimReport) *entities.InterimReport {
	if report == nil {
		return nil
	}

	// Process each finding (file) in the report
	for i := range report.Findings {
		finding := &report.Findings[i]
		finding.CryptographicAssets = deduplicateAssets(finding.FilePath, finding.CryptographicAssets)
	}

	return report
}

// deduplicateAssets deduplicates a slice of cryptographic assets based on their identity and location.
func deduplicateAssets(filePath string, assets []entities.CryptographicAsset) []entities.CryptographicAsset {
	if len(assets) <= 1 {
		return assets
	}

	// Group assets by their identity (file path + asset key + location)
	assetGroups := make(map[assetGroupKey][]entities.CryptographicAsset)
	firstSeenKeys := make([]assetGroupKey, 0)

	for i := range assets {
		asset := &assets[i]
		// Generate the asset key using the entity's GetKey method
		// This provides asset-type-specific identity based on identifying metadata fields
		assetKey := asset.GetKey()

		key := assetGroupKey{
			filePath:  filePath,
			assetKey:  assetKey,
			startLine: asset.StartLine,
			endLine:   asset.EndLine,
		}

		if _, exists := assetGroups[key]; !exists {
			firstSeenKeys = append(firstSeenKeys, key)
		}

		assetGroups[key] = append(assetGroups[key], *asset)
	}

	deduplicated := make([]entities.CryptographicAsset, 0, len(assetGroups))
	for _, key := range firstSeenKeys {
		group := assetGroups[key]
		mergedAsset := mergeAssets(group)
		deduplicated = append(deduplicated, mergedAsset)
	}

	return deduplicated
}

// mergeAssets merges multiple CryptographicAssets with the same identity into one.
// It preserves all unique metadata from all assets in the group.
//
// Merge strategy:
// - Uses the first asset as the base
// - Preserves the first asset's match text (they should be identical for same location)
// - Merges all rules from all assets into the Rules array, preserving unique rules
// - Merges all unique metadata key-value pairs from all assets
// - Maintains the most severe status if different.
func mergeAssets(assets []entities.CryptographicAsset) entities.CryptographicAsset {
	if len(assets) == 1 {
		return assets[0]
	}

	// Use the first asset as the base
	merged := assets[0]

	// Ensure metadata map is initialized
	if merged.Metadata == nil {
		merged.Metadata = make(map[string]string)
	}

	// Track unique rule IDs to avoid duplicates
	seenRules := make(map[string]bool)
	for _, rule := range merged.Rules {
		seenRules[rule.ID] = true
	}

	// Merge metadata and rules from all assets
	for i := 1; i < len(assets); i++ {
		asset := assets[i]

		// Merge unique metadata values (keep first value on conflicts)
		for key, value := range asset.Metadata {
			// Only add if the key doesn't exist
			if _, exists := merged.Metadata[key]; !exists {
				merged.Metadata[key] = value
			}
		}

		// Merge rules - add any new unique rules
		for _, rule := range asset.Rules {
			if !seenRules[rule.ID] {
				merged.Rules = append(merged.Rules, rule)
				seenRules[rule.ID] = true
			}
		}
	}

	return merged
}
