// Copyright (C) 2026 SCANOSS.COM
// SPDX-License-Identifier: GPL-2.0-only
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; version 2.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

package skip

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
)

const generatedHeaderReadLimit = 4096

var generatedHeaderMarkers = [][]byte{
	[]byte("Generated by the protocol buffer compiler"),
	[]byte("Code generated by protoc-gen-go"),
	[]byte("Code generated by protoc-gen-grpc"),
	[]byte("@generated by prost-build"),
	[]byte("automatically generated by rust-bindgen"),
	[]byte("GENERATED CODE -- DO NOT EDIT"),
}

// sourceMatcher applies gitignore path patterns and, when enabled, a
// high-confidence generated-source header check. Protobuf runtimes that
// are the artifact under scan stay in scope; copies under a shaded/
// segment are still skipped.
type sourceMatcher struct {
	paths          *GitIgnoreMatcher
	inspectHeaders bool
}

// NewDefaultMatcher returns the built-in skip policy: default directories,
// generated-stub globs, and protobuf/prost/bindgen compiler headers.
func NewDefaultMatcher() SkipMatcher {
	return NewMatcher(DefaultPatterns(), true)
}

// NewMatcher builds a skip matcher from gitignore-style patterns.
// inspectHeaders enables the protocol-buffer / prost / bindgen header
// check. Pass false when --no-default-exclusions is set so the new
// default policy is fully disabled.
func NewMatcher(patterns []string, inspectHeaders bool) SkipMatcher {
	return &sourceMatcher{
		paths:          NewGitIgnoreMatcher(patterns),
		inspectHeaders: inspectHeaders,
	}
}

// ShouldSkip reports whether path should be excluded from scanning.
func (m *sourceMatcher) ShouldSkip(path string, isDir bool) bool {
	if isDir {
		return m.paths.ShouldSkip(path, true)
	}
	if !m.inspectHeaders {
		return m.paths.ShouldSkip(path, false)
	}
	slash := filepath.ToSlash(path)
	if pathHasSegment(slash, "shaded") {
		return true
	}
	if isProtobufRuntimePath(slash) {
		return false
	}
	if m.paths.ShouldSkip(path, false) {
		return true
	}
	return hasGeneratedSourceHeader(path)
}

func pathHasSegment(slashPath, segment string) bool {
	for _, part := range strings.Split(slashPath, "/") {
		if part == segment {
			return true
		}
	}
	return false
}

func isProtobufRuntimePath(slashPath string) bool {
	p := slashPath
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	return strings.Contains(p, "/com/google/protobuf/") ||
		strings.HasSuffix(p, "/com/google/protobuf") ||
		strings.Contains(p, "/google/protobuf/") ||
		strings.HasSuffix(p, "/google/protobuf") ||
		strings.Contains(p, "google.golang.org/protobuf") ||
		strings.Contains(p, "github.com/protocolbuffers/protobuf")
}

func hasGeneratedSourceHeader(path string) bool {
	if !maybeGeneratedExtension(path) {
		return false
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	buf := make([]byte, generatedHeaderReadLimit)
	n, err := f.Read(buf)
	if closeErr := f.Close(); closeErr != nil && n == 0 {
		return false
	}
	if n == 0 && err != nil {
		return false
	}
	head := buf[:n]
	for _, marker := range generatedHeaderMarkers {
		if bytes.Contains(head, marker) {
			return true
		}
	}
	return false
}

func maybeGeneratedExtension(path string) bool {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".java", ".py", ".go", ".js", ".ts", ".cc", ".h", ".hh", ".hpp", ".hxx", ".cpp", ".cxx", ".rs":
		return true
	default:
		return false
	}
}
