// Copyright (C) 2026 SCANOSS.COM
// SPDX-License-Identifier: GPL-2.0-only
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; version 2.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

package skip

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDefaultPatternsSkipShadedAndGeneratedStubs(t *testing.T) {
	t.Parallel()

	matcher := NewDefaultMatcher()
	cases := []struct {
		path  string
		isDir bool
		skip  bool
	}{
		{path: "io/grpc/xds/shaded", isDir: true, skip: true},
		{path: "io/grpc/xds/shaded/io/envoyproxy/envoy/config/core/v3/Address.java", isDir: false, skip: true},
		{path: "src/main/java/com/example/FooOuterClass.java", isDir: false, skip: true},
		{path: "pkg/foo_pb2.py", isDir: false, skip: true},
		{path: "pkg/foo_pb2_grpc.py", isDir: false, skip: true},
		{path: "api/v1/types.pb.go", isDir: false, skip: true},
		{path: "pkg/apis/zz_generated.deepcopy.go", isDir: false, skip: true},
		{path: "src/foo_pb.js", isDir: false, skip: true},
		{path: "src/foo_pb.ts", isDir: false, skip: true},
		{path: "proto/service.pb.cc", isDir: false, skip: true},
		{path: "proto/service.pb.h", isDir: false, skip: true},
		{path: "proto/service.grpc.pb.cc", isDir: false, skip: true},
		{path: "proto/service.grpc.pb.h", isDir: false, skip: true},
		{path: "src/main/java/com/example/Cipher.java", isDir: false, skip: false},
		{path: "pkg/crypto.py", isDir: false, skip: false},
		{path: "src/lib.rs", isDir: false, skip: false},
	}
	for _, tc := range cases {
		if got := matcher.ShouldSkip(tc.path, tc.isDir); got != tc.skip {
			t.Errorf("ShouldSkip(%q, %v) = %v, want %v", tc.path, tc.isDir, got, tc.skip)
		}
	}
}

func TestDefaultMatcherSkipsProtobufCompilerHeader(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	authored := filepath.Join(dir, "Cipher.java")
	generated := filepath.Join(dir, "Messages.java")
	runtime := filepath.Join(dir, "com", "google", "protobuf", "DescriptorProtos.java")
	if err := os.MkdirAll(filepath.Dir(runtime), 0o755); err != nil {
		t.Fatalf("mkdir runtime: %v", err)
	}
	writeFile(t, authored, "package com.example;\npublic class Cipher { public void encrypt() {} }\n")
	writeFile(t, generated, "// Generated by the protocol buffer compiler.  DO NOT EDIT!\npackage com.example;\npublic class Messages {}\n")
	writeFile(t, runtime, "// Generated by the protocol buffer compiler.  DO NOT EDIT!\npackage com.google.protobuf;\npublic class DescriptorProtos {}\n")

	matcher := NewDefaultMatcher()
	if matcher.ShouldSkip(authored, false) {
		t.Errorf("authored source %q should be scanned", authored)
	}
	if !matcher.ShouldSkip(generated, false) {
		t.Errorf("protobuf compiler header in %q should be skipped", generated)
	}
	if matcher.ShouldSkip(runtime, false) {
		t.Errorf("protobuf-java runtime %q should stay in scope", runtime)
	}
}

func TestDefaultMatcherSkipsRustGeneratedHeadersBesideSources(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	lib := filepath.Join(dir, "lib.rs")
	prost := filepath.Join(dir, "envoy.rs")
	bindgen := filepath.Join(dir, "bindings.rs")
	writeFile(t, lib, "pub fn encrypt() {}\n")
	writeFile(t, prost, "// @generated by prost-build\npub struct Address {}\n")
	writeFile(t, bindgen, "/* automatically generated by rust-bindgen 0.69.1 */\npub type Foo = i32;\n")

	matcher := NewDefaultMatcher()
	if matcher.ShouldSkip(lib, false) {
		t.Errorf("authored crate source %q should be scanned", lib)
	}
	if !matcher.ShouldSkip(prost, false) {
		t.Errorf("prost generated %q should be skipped", prost)
	}
	if !matcher.ShouldSkip(bindgen, false) {
		t.Errorf("bindgen generated %q should be skipped", bindgen)
	}
}

func TestDefaultMatcherKeepsProtobufRuntimeArtifact(t *testing.T) {
	t.Parallel()

	matcher := NewDefaultMatcher()
	keep := []string{
		"com/google/protobuf/DescriptorProtos.java",
		"google/protobuf/descriptor_pb2.py",
		"google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go",
	}
	for _, path := range keep {
		if matcher.ShouldSkip(path, false) {
			t.Errorf("protobuf runtime %q should stay in scope", path)
		}
	}
}

func TestNoDefaultExclusionsDropGeneratedPatternsAndHeaders(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	generated := filepath.Join(dir, "Messages.java")
	writeFile(t, generated, "// Generated by the protocol buffer compiler.  DO NOT EDIT!\nclass Messages {}\n")

	empty := NewMatcher(nil, false)
	if empty.ShouldSkip("io/grpc/xds/shaded", true) {
		t.Fatal("shaded dir should not be skipped when default exclusions are off")
	}
	if empty.ShouldSkip("pkg/foo_pb2.py", false) {
		t.Fatal("generated filename should not be skipped when default exclusions are off")
	}
	if empty.ShouldSkip(generated, false) {
		t.Fatal("compiler header should not be skipped when default exclusions are off")
	}
}

func TestDefaultsSourceIncludesGeneratedPatterns(t *testing.T) {
	t.Parallel()

	patterns, err := NewDefaultsSource().Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	for _, want := range []string{"shaded", "**/*_pb2.py", "**/*.pb.go", "**/*OuterClass.java"} {
		if !containsPattern(patterns, want) {
			t.Errorf("DefaultsSource missing %q in %v", want, patterns)
		}
	}
	if !strings.Contains(strings.Join(DefaultPatterns(), ","), "**/*_pb2.py") {
		t.Fatal("DefaultPatterns should include generated stub globs")
	}
}

func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
